server:
  port: 9001

# 将网关服务注册到Eureka Server中
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
spring:
  application:
    name: egobuy-gateway

# 设置请求前缀
zuul:
  prefix: /api
  routes:
    egobuy-shop-service: /shop/**
    egobuy-file: /file/**
    egobuy-content-service: /cms/**
# Ribbon超时时间
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

# Hystrix断路触发时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
